# Generated by Django 3.2.13 on 2022-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220710_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_review_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата відгука'),
        ),
    ]
